### ISSUE TITLE
Contribution process gamification

### ISSUE THREAD

**Issue by olegcherev** [nelsonic/nelsonic.github.io#913]
Hi @nelsonic,

What do you think of the idea of gamifying the open source contributions? may it encourage the community to contribute more...?

I made a GitHub app that implements elements like XP for commits/PRs/issues, Levels, Leaderboard, Challenges, Badges. This may work for community, especially first-time contributors to contribute more with no efforts from maintainer

It looks it fits well with dwyl concept/vision/values. I'd appreciate your feedback. 

There's a [Live Demo](https://demo.devactivity.com/achievements/?activeTab=achievements&organizationId=1) (no auth required) and [Public Dashboard Demo](https://demo.devactivity.com/public/?organizationLogin=demo-organization&organizationId=1)

**Comment by nelsonic** [comment]
Hi @olegcherev, 👋 
Apologies for delayed reply I've been racing towards a deadline and couldn't do anything `else`. ⏳ 
I've had a good look at your site https://devactivity.com

<img width="1156" alt="image" src="https://github.com/user-attachments/assets/602134e0-224b-4bde-a818-bb2f0ad3b6f8">

<img width="1156" alt="image" src="https://github.com/user-attachments/assets/82d63ee3-ff5e-4087-9cd9-415a2af2c08a">

And even attempted to click the "Learn more about [devActivity](https://github.com/undefined?organizationId=1)" on your site but it's a `404`: 
<img width="1102" alt="devactivity" src="https://github.com/user-attachments/assets/2f80c6f7-ce61-421f-8c00-de23c09b756e">

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/f9e64e7f-ee5d-4d2f-8c3b-dd32f8cd7dd8">

Consider fixing it. 🔗 💔 

My reading of your `GitHub` is that your `App` is Closed Source ...
https://github.com/devactivity-app
![image](https://github.com/user-attachments/assets/c2b1848d-d448-402b-b2ba-1e51672f2474)

And the only thing that is Open is the discussion forum: https://github.com/orgs/devactivity-app/discussions

<img width="1403" alt="image" src="https://github.com/user-attachments/assets/dd7bab17-c6b1-4d13-be33-1ab58428c5ae">

https://devactivity.com/pricing/ what is an "active" contributor? How do you define it? 
<img width="1258" alt="image" src="https://github.com/user-attachments/assets/1297f802-dbb5-4416-9901-b8a8ebd8037c">

In the FAQ:
<img width="553" alt="image" src="https://github.com/user-attachments/assets/ebbed78d-d58b-4624-ad4f-de71436f737e">

But what is "actively"? is it once a month? 🤷‍♂️ 

In a _small_ Open Source team this pricing model _discourages_ adding contributors because each one is an additional $10-$20/month. ($120-$240/year!)

Sadly, this is a total deal-breaker. 
Consider an Open Source is Free Model to collect more data and gain exposure.
That's what 

Also from _many_ years experience at more companies than I can count,
gamifying these metrics is a recipe for busywork; i.e. **quantity and not high _quality_ output**. 

# “_Do not confuse motion and progress. A rocking horse keeps moving but does not make any progress_.” ~ Alfred A. Montapert

Having said all this, you clearly have skills at building a product! 🙌 
Keep up the work. 👍 
Best of luck with it. 🍀

**Comment by olegcherev** [comment]
@nelsonic Thank you for the feedback! devActivity is closed sourced, but totally free for Open Source teams and free for small teams (up to 7 contributors). Commercial teams may benefit from Performance Reviews, Retrospective Insights and Alerts besides the Gamification feature.

Also, I agree that greater output != greater outcomes, but with proper product/project management it leads to greater results.

Thank you
